### ISSUE TITLE
No Unity Package for v0.0.7

### ISSUE THREAD

**Issue by Proshi** [NotAKidOnSteam/AASEmulator#19]
This Hurts Brain of Friend. 

Where Pakag
Pls? 

We Need for Demonstration.

**Comment by NotAKidOnSteam** [comment]
im fuckin tired, this week has been busy
https://github.com/NotAKidOnSteam/AASEmulator/releases/download/v0.0.7/AASEmulator_v0.0.7.unitypackage

**Comment by Proshi** [comment]
It's fine
